[versions]
kotlin = "1.7.20"
gradleplugin = "7.3.1"

kotest = "5.4.2"
ktlint = "0.46.1"
kover = "0.5.1"
spotless = "6.9.0"
junit4 = "4.13.2"

compose = "1.3.0-beta03"
material3 = "1.0.1"
navigation-compose = "2.5.2"
activity-compose = "1.6.0"
splashscreen = "1.0.0"
accompanist = "0.26.4-beta"
constraintlayout = "1.0.1"
lifecycle = "2.5.1"
profileinstaller = "1.2.0"

core-ktx = "1.9.0"
appcompat = "1.6.0-rc01"
desugar = "1.2.2"
coroutines = "1.6.4"

mockk = "1.12.0"
data-store = "1.0.0"
coil = "2.1.0"
ktor = "2.0.3"
slf4j = "1.3.0-beta0"
datetime = "0.4.0"

ylib = "0.2.0"
recompose = "0.1.0.42-SNAPSHOT" #FIXME: release the new recompose version.

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotest-jvm-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
y-core = { module = "com.github.whyrising.y:y-core", version.ref = "ylib" }
y-concurrency = { module = "com.github.whyrising.y:y-concurrency", version.ref = "ylib" }
recompose = { module = "com.github.whyrising.recompose:recompose", version.ref = "recompose" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-android-plugin = { module = "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin", version.ref = "kotlin" }
android-library-gradle-plugin = { module = "com.android.library:com.android.library.gradle.plugin", version.ref = "gradleplugin" }
android-application-gradle-plugin = { module = "com.android.application:com.android.application.gradle.plugin", version.ref = "gradleplugin" }
androidx-activity-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
androidx-compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-compose-material-icons-ext = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
androidx-compose-material3-windowssizeclass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
android-tools-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
accompanist-nav-anim = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockkjvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }
androidx-datastore-prefrences = { module = "androidx.datastore:datastore-preferences", version.ref = "data-store" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
slf4j = { module = "ch.qos.logback:logback-classic", version.ref = "slf4j" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

[bundles]
compose = ["androidx-compose-ui-ui", "androidx-compose-ui-util", "androidx-compose-ui-tooling", "androidx-compose-material3", "androidx-constraintlayout-compose", "accompanist-swiperefresh", "androidx-compose-material3-windowssizeclass", "androidx-profileinstaller", "androidx-compose-material-icons-ext"]
kotest = ["kotest-jvm-runner", "kotest-assertions", "kotlin-reflect"]
ktor = ["ktor-client-core", "ktor-client-android", "ktor-client-contentnegotiation", "ktor-serialization-json", "ktor-client-logging", "slf4j"]

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
